### ISSUE TITLE
Make yourself at home: Hierro

### ISSUE THREAD

**Issue by AaronNHart** [AaronNHart/bootstrap#2]
## Markdown
1. Write up a list of topics you are interested in learning about using a _text editor_. 
2. Use the .md file extension to flag your text file as a _markdown_ document. 
3. For each topic, try to break it down into smaller pieces. Use different _header levels_ to organize your document.  
4. Add at least one _link_ using markdown to point to related materials (eg. games you like, apps, etc). 

## Github
1. _Install_ github desktop.
2. _Clone_ my bootstrap repository.
3. Create a _branch_ in this project for your work. 
4. Submit a _pull request_ asking me to add your list of interesting topic to the master branch under the submissions folder.

**Comment by Hierro2002** [comment]
ok
